[sccm]
username = DOMAIN\user
password = password
report_computers = https://conman/ReportServer?%2F
report_network = https://conman/ReportServer?%2F
report_edr = https://conman/ReportServer?%2F

[medigate]
url = https://api.medigate.io/api/v1/
apikey = api_key

[ldap]
laps_user = laps_admin
domain = domain.example.com
bind_dn = cn=user,dc=domain,dc=example,dc=com
password = password
ldap_base = dc=domain,dc=example,dc=com
search_bases = ou=Computers,dc=domain,dc=example,dc=com
ldap_filter = (&(objectCategory=computer))

[csv]
input = SURVEY/IN
output = SURVEY/PROCESSED

[ordr]
username = user
password = password
url = https://ordr.domain.example.com
# ORDR can't seem to implement chained certs
tls_verify = False

[snipe-it]
#Required
url = https://snipeit.example.com
apikey = api_key
# These are people or departments that are not automatically checked out because they login to other people's computers
techs = user1 user2 dept1 dept2

[jamf]
# This entire section is Required
url = https://jamf.example.com
username = user
password = pass

# This is for the Ansible script
[Darwin-api-mapping]
# REQUIRED
asset_tag = facter_system_profiler hardware_uuid
serial = facter_system_profiler serial_number
model = facter_system_profiler model_identifier
manufacturer = | {{ 'Apple' }}
# For each interfaces you want to map, add a new line with the mac address
mac_addresses = facter_networking interfaces | {{ var.values() | selectattr('mac', 'defined') | map(attribute='mac') | list }}
operating_system = facter_os macosx product
os_type = | {{ 'Other' }}
os_version = facter_os macosx version full
os_build = facter_os macosx build
ram = facter_memory system total_bytes | {{ var / 1024 / 1024 }}
cpu = facter_processors models | {{ (var | first) if var }}
storage = facter_disks models | {{ (var | first) if var }}
current_user = current_user
domain = ad_domain
org_unit = ad_ou
edr = edr
management = | {{ 'Ansible ' }}
ip_address = all_ipv4_addresses | {{ (var | last) if var }}

[Linux-api-mapping]
#...
[Win32NT-api-mapping]
#...
[FreeBSD-api-mapping]
#...