[sccm]
username = DOMAIN\username
password = password
report1 = https://sccm/atom-url
report2 = https://sccm/atom-url
report1_namespace = Machine_Info_Discovered_and_Managed
report2_namespace = http://schemas.microsoft.com/ado/2007/08/dataservices

[ansible]
# This entire section is Required
url = your-ansible-cache
os = Linux,FreeBSD,Win32NT
# Darwin is done with jamf2snipeit

[snipe-it]
#Required
url = http://your-snipe-it-url
apikey = your-api-key
computer_status = 2
mobile_status = 2
embedded_status = 2
network_status = 2
printer_status = 2

computer_category = 2
mobile_category = 3
embedded_category = 4
network_category = 5
printer_category = 6

computer_custom_fieldset_id = 1
mobile_custom_fieldset_id = 2
embedded_custom_fieldset_id = 3
network_custom_fieldset_id = 4
printer_custom_fieldset_id = 5

technicians = list of users that should not be checked out

# EDIT THESE FIELDS SO THEY CORRESPOND WITH THE CUSTOM FIELD DB COLUMN NAMES IN YOUR SNIPE-IT INSTANCE
[Linux-api-mapping]
device_type = computer
# REQUIRED
asset_tag = ansible_chassis_asset_tag
serial = ansible_product_serial
# Set this to something always unique, like the UUID
unique_tag = ansible_product_uuid
model = ansible_product_name
manufacturer = ansible_system_vendor
# OPTIONAL
_snipeit_mac_address_1 = ansible_default_ipv4 macaddress
_snipeit_ram_2 = ansible_memtotal_mb
_snipeit_operating_system_8 = ansible_distribution
_snipeit_os_version_9 = ansible_distribution_version
_snipeit_os_build_10 = ansible_kernel
_snipeit_cpu_name_14 = ansible_processor 0

# Required if mapping users to computers
user_field = user_sessions 0 UserName

[Win32NT-api-mapping]
device_type = computer
# REQUIRED
serial = ansible_product_serial
unique_tag = ansible_machine_id
model = ansible_product_name
manufacturer = ansible_system_vendor
# OPTIONAL
_snipeit_mac_address_1 = ansible_interfaces 0 macaddress
_snipeit_ram_2 = ansible_memtotal_mb
_snipeit_mac_address_2_5 = ansible_interfaces 1 macaddress
_snipeit_mac_address_3_6 = ansible_interfaces 2 macaddress
_snipeit_mac_address_4_7 = ansible_interfaces 3 macaddress
_snipeit_operating_system_8 = ansible_distribution
_snipeit_os_version_9 = ansible_distribution_version
# Required if mapping users to computers
user_field = user_sessions 0 UserName
_snipeit_cpu_name_14 = ansible_processor 2

[FreeBSD-api-mapping]
device_type = computer
# REQUIRED
serial = ansible_product_serial
model = ansible_product_name
manufacturer = ansible_system_vendor
# OPTIONAL
_snipeit_mac_address_1 = ansible_default_ipv4 macaddress
_snipeit_ram_2 = ansible_memtotal_mb
_snipeit_operating_system_8 = ansible_distribution
_snipeit_os_version_9 = ansible_distribution_version
_snipeit_os_build_10 = ansible_distribution_release
# Required if mapping users to computers
user_field = user_sessions 0 UserName
_snipeit_cpu_name_14 = ansible_processor 0
